# Generated by Django 6.0.2 on 2026-02-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
